= {documentation}[Account Ledger]
:author:        Edwyn Tech
:owner:         Edwyntech
:email:         mailto:contact@edwyn.tech
:project:       mowitnow
:key:           {owner}_{project}
:repo:          https://github.com/{owner}/{project}
:documentation: https://{owner}.github.io/{project}
:cicd:          {repo}/actions/workflows/cicd.yaml
:linkedin:      https://www.linkedin.com/company/74937487/
:youtube:       https://www.youtube.com/@EdwynTech
:twitch:        https://www.twitch.tv/edwyntech
:badges:        https://img.shields.io/badge

image:{cicd}/badge.svg[link={cicd},window=_blank]

Un livre de comptes mis à jour à l'aide de link:https://kafka.apache.org/documentation/streams/[Kafka Streams^].

== Structure

Ce projet est construit comme un projet Maven multi-module basé sur le JDK 21.

Parmi ces modules :

* `avro` - Les schémas link:https://avro.apache.org[Avro^].
* `domain` - Le domaine fonctionnel de l'application.
* `application` - L'environnement d'exécution de l'application.
* `documentation` - La documentation vivante du projet.

[NOTE]
====
Les répertoires qui démarrent par un point contiennent des configurations additionnelles :

* `.github` - configure le CICD
* `.idea` - configure IntelliJ
* `.mvn` - configure la toolchain Maven
====

== Cycle De Vie

|===

|Construction|./mvnw package
|Documentation|./mvnw verify
|Lancement|./mvnw spring-boot:run
|===

[TIP]
====
Le lancement se fait par défaut en se connectant à un broker Kafka externe.

Si vous souhaitez lancer l'application tous les éléments disponibles, il est possible de lancer la commande

  `./mvnw spring-boot:run -Dspring-boot.run.profiles=docker`

Elle déclenchera un docker compose qui lancera :

* link:https://zookeeper.apache.org[Zookeeper^]
* link:https://kafka.apache.org[Kafka^]
* link:https://www.confluent.io[Schema registry^]
* link:https://akhq.io[AKHQ^]

La description des composants lancés se trouve dans le fichier `docker-compose.yaml`.
====

== Auteur

image::https://img.shields.io/badge/Par_email-email?style=social&logo=microsoftoutlook&label={author}[link={email}]
image::{badges}/Sur_LinkedIn-email?style=social&logo=linkedin&label={author}[link={linkedin},window=_blank]
image::https://img.shields.io/badge/Youtube-channel?style=social&logo=youtube&label={author}[link={youtube},window=_blank]
image::https://img.shields.io/badge/Twitch-channel?style=social&logo=twitch&label={author}[link={twitch},window=_blank]
